package cn.com.gxbolian.databank.entity;

import java.io.Serializable;
import java.util.Date;

public class XtpzTableGxh  implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_table_gxh.lsh
     *
     * @mbg.generated
     */
    private String lsh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_table_gxh.czybm
     *
     * @mbg.generated
     */
    private String czybm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_table_gxh.mc
     *
     * @mbg.generated
     */
    private String mc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_table_gxh.bm
     *
     * @mbg.generated
     */
    private String bm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_table_gxh.scsj
     *
     * @mbg.generated
     */
    private Date scsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_table_gxh.sxsj
     *
     * @mbg.generated
     */
    private Date sxsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_table_gxh.zt
     *
     * @mbg.generated
     */
    private String zt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_table_gxh.lsh
     *
     * @return the value of xtpz_table_gxh.lsh
     *
     * @mbg.generated
     */
    public String getLsh() {
        return lsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_table_gxh.lsh
     *
     * @param lsh the value for xtpz_table_gxh.lsh
     *
     * @mbg.generated
     */
    public void setLsh(String lsh) {
        this.lsh = lsh == null ? null : lsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_table_gxh.czybm
     *
     * @return the value of xtpz_table_gxh.czybm
     *
     * @mbg.generated
     */
    public String getCzybm() {
        return czybm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_table_gxh.czybm
     *
     * @param czybm the value for xtpz_table_gxh.czybm
     *
     * @mbg.generated
     */
    public void setCzybm(String czybm) {
        this.czybm = czybm == null ? null : czybm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_table_gxh.mc
     *
     * @return the value of xtpz_table_gxh.mc
     *
     * @mbg.generated
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_table_gxh.mc
     *
     * @param mc the value for xtpz_table_gxh.mc
     *
     * @mbg.generated
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_table_gxh.bm
     *
     * @return the value of xtpz_table_gxh.bm
     *
     * @mbg.generated
     */
    public String getBm() {
        return bm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_table_gxh.bm
     *
     * @param bm the value for xtpz_table_gxh.bm
     *
     * @mbg.generated
     */
    public void setBm(String bm) {
        this.bm = bm == null ? null : bm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_table_gxh.scsj
     *
     * @return the value of xtpz_table_gxh.scsj
     *
     * @mbg.generated
     */
    public Date getScsj() {
        return scsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_table_gxh.scsj
     *
     * @param scsj the value for xtpz_table_gxh.scsj
     *
     * @mbg.generated
     */
    public void setScsj(Date scsj) {
        this.scsj = scsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_table_gxh.sxsj
     *
     * @return the value of xtpz_table_gxh.sxsj
     *
     * @mbg.generated
     */
    public Date getSxsj() {
        return sxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_table_gxh.sxsj
     *
     * @param sxsj the value for xtpz_table_gxh.sxsj
     *
     * @mbg.generated
     */
    public void setSxsj(Date sxsj) {
        this.sxsj = sxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_table_gxh.zt
     *
     * @return the value of xtpz_table_gxh.zt
     *
     * @mbg.generated
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_table_gxh.zt
     *
     * @param zt the value for xtpz_table_gxh.zt
     *
     * @mbg.generated
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }
}