package cn.com.gxbolian.databank.entity;

import java.io.Serializable;

public class XtpzXlcs  implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_xlcs.lsh
	 * @mbg.generated
	 */
	private String lsh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_xlcs.zdbm
	 * @mbg.generated
	 */
	private String zdbm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_xlcs.xsz
	 * @mbg.generated
	 */
	private String xsz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_xlcs.sjz
	 * @mbg.generated
	 */
	private String sjz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_xlcs.tzbz
	 * @mbg.generated
	 */
	private String tzbz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_xlcs.ybmc
	 * @mbg.generated
	 */
	private String ybmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_xlcs.ybzd
	 * @mbg.generated
	 */
	private String ybzd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_xlcs.lsh
	 * @return  the value of xtpz_xlcs.lsh
	 * @mbg.generated
	 */
	public String getLsh() {
		return lsh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_xlcs.lsh
	 * @param lsh  the value for xtpz_xlcs.lsh
	 * @mbg.generated
	 */
	public void setLsh(String lsh) {
		this.lsh = lsh == null ? null : lsh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_xlcs.zdbm
	 * @return  the value of xtpz_xlcs.zdbm
	 * @mbg.generated
	 */
	public String getZdbm() {
		return zdbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_xlcs.zdbm
	 * @param zdbm  the value for xtpz_xlcs.zdbm
	 * @mbg.generated
	 */
	public void setZdbm(String zdbm) {
		this.zdbm = zdbm == null ? null : zdbm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_xlcs.xsz
	 * @return  the value of xtpz_xlcs.xsz
	 * @mbg.generated
	 */
	public String getXsz() {
		return xsz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_xlcs.xsz
	 * @param xsz  the value for xtpz_xlcs.xsz
	 * @mbg.generated
	 */
	public void setXsz(String xsz) {
		this.xsz = xsz == null ? null : xsz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_xlcs.sjz
	 * @return  the value of xtpz_xlcs.sjz
	 * @mbg.generated
	 */
	public String getSjz() {
		return sjz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_xlcs.sjz
	 * @param sjz  the value for xtpz_xlcs.sjz
	 * @mbg.generated
	 */
	public void setSjz(String sjz) {
		this.sjz = sjz == null ? null : sjz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_xlcs.tzbz
	 * @return  the value of xtpz_xlcs.tzbz
	 * @mbg.generated
	 */
	public String getTzbz() {
		return tzbz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_xlcs.tzbz
	 * @param tzbz  the value for xtpz_xlcs.tzbz
	 * @mbg.generated
	 */
	public void setTzbz(String tzbz) {
		this.tzbz = tzbz == null ? null : tzbz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_xlcs.ybmc
	 * @return  the value of xtpz_xlcs.ybmc
	 * @mbg.generated
	 */
	public String getYbmc() {
		return ybmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_xlcs.ybmc
	 * @param ybmc  the value for xtpz_xlcs.ybmc
	 * @mbg.generated
	 */
	public void setYbmc(String ybmc) {
		this.ybmc = ybmc == null ? null : ybmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_xlcs.ybzd
	 * @return  the value of xtpz_xlcs.ybzd
	 * @mbg.generated
	 */
	public String getYbzd() {
		return ybzd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_xlcs.ybzd
	 * @param ybzd  the value for xtpz_xlcs.ybzd
	 * @mbg.generated
	 */
	public void setYbzd(String ybzd) {
		this.ybzd = ybzd == null ? null : ybzd.trim();
	}
}