package cn.com.gxbolian.databank.entity;

import java.io.Serializable;

public class XtpzBzhzjpzSr implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sr.lsh
	 * @mbg.generated
	 */
	private String lsh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sr.bzhlsh
	 * @mbg.generated
	 */
	private String bzhlsh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sr.zdmc
	 * @mbg.generated
	 */
	private String zdmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sr.sjlx
	 * @mbg.generated
	 */
	private String sjlx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sr.xlzdbm
	 * @mbg.generated
	 */
	private String xlzdbm;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sr.lsh
	 * @return  the value of xtpz_bzhzjpz_sr.lsh
	 * @mbg.generated
	 */
	public String getLsh() {
		return lsh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sr.lsh
	 * @param lsh  the value for xtpz_bzhzjpz_sr.lsh
	 * @mbg.generated
	 */
	public void setLsh(String lsh) {
		this.lsh = lsh == null ? null : lsh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sr.bzhlsh
	 * @return  the value of xtpz_bzhzjpz_sr.bzhlsh
	 * @mbg.generated
	 */
	public String getBzhlsh() {
		return bzhlsh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sr.bzhlsh
	 * @param bzhlsh  the value for xtpz_bzhzjpz_sr.bzhlsh
	 * @mbg.generated
	 */
	public void setBzhlsh(String bzhlsh) {
		this.bzhlsh = bzhlsh == null ? null : bzhlsh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sr.zdmc
	 * @return  the value of xtpz_bzhzjpz_sr.zdmc
	 * @mbg.generated
	 */
	public String getZdmc() {
		return zdmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sr.zdmc
	 * @param zdmc  the value for xtpz_bzhzjpz_sr.zdmc
	 * @mbg.generated
	 */
	public void setZdmc(String zdmc) {
		this.zdmc = zdmc == null ? null : zdmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sr.sjlx
	 * @return  the value of xtpz_bzhzjpz_sr.sjlx
	 * @mbg.generated
	 */
	public String getSjlx() {
		return sjlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sr.sjlx
	 * @param sjlx  the value for xtpz_bzhzjpz_sr.sjlx
	 * @mbg.generated
	 */
	public void setSjlx(String sjlx) {
		this.sjlx = sjlx == null ? null : sjlx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sr.xlzdbm
	 * @return  the value of xtpz_bzhzjpz_sr.xlzdbm
	 * @mbg.generated
	 */
	public String getXlzdbm() {
		return xlzdbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sr.xlzdbm
	 * @param xlzdbm  the value for xtpz_bzhzjpz_sr.xlzdbm
	 * @mbg.generated
	 */
	public void setXlzdbm(String xlzdbm) {
		this.xlzdbm = xlzdbm == null ? null : xlzdbm.trim();
	}
}