package cn.com.gxbolian.databank.entity;

import java.util.ArrayList;
import java.util.List;

public class XtpzSjyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    public XtpzSjyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSjybmIsNull() {
            addCriterion("sjybm is null");
            return (Criteria) this;
        }

        public Criteria andSjybmIsNotNull() {
            addCriterion("sjybm is not null");
            return (Criteria) this;
        }

        public Criteria andSjybmEqualTo(String value) {
            addCriterion("sjybm =", value, "sjybm");
            return (Criteria) this;
        }

        public Criteria andSjybmNotEqualTo(String value) {
            addCriterion("sjybm <>", value, "sjybm");
            return (Criteria) this;
        }

        public Criteria andSjybmGreaterThan(String value) {
            addCriterion("sjybm >", value, "sjybm");
            return (Criteria) this;
        }

        public Criteria andSjybmGreaterThanOrEqualTo(String value) {
            addCriterion("sjybm >=", value, "sjybm");
            return (Criteria) this;
        }

        public Criteria andSjybmLessThan(String value) {
            addCriterion("sjybm <", value, "sjybm");
            return (Criteria) this;
        }

        public Criteria andSjybmLessThanOrEqualTo(String value) {
            addCriterion("sjybm <=", value, "sjybm");
            return (Criteria) this;
        }

        public Criteria andSjybmLike(String value) {
            addCriterion("sjybm like", value, "sjybm");
            return (Criteria) this;
        }

        public Criteria andSjybmNotLike(String value) {
            addCriterion("sjybm not like", value, "sjybm");
            return (Criteria) this;
        }

        public Criteria andSjybmIn(List<String> values) {
            addCriterion("sjybm in", values, "sjybm");
            return (Criteria) this;
        }

        public Criteria andSjybmNotIn(List<String> values) {
            addCriterion("sjybm not in", values, "sjybm");
            return (Criteria) this;
        }

        public Criteria andSjybmBetween(String value1, String value2) {
            addCriterion("sjybm between", value1, value2, "sjybm");
            return (Criteria) this;
        }

        public Criteria andSjybmNotBetween(String value1, String value2) {
            addCriterion("sjybm not between", value1, value2, "sjybm");
            return (Criteria) this;
        }

        public Criteria andSjymcIsNull() {
            addCriterion("sjymc is null");
            return (Criteria) this;
        }

        public Criteria andSjymcIsNotNull() {
            addCriterion("sjymc is not null");
            return (Criteria) this;
        }

        public Criteria andSjymcEqualTo(String value) {
            addCriterion("sjymc =", value, "sjymc");
            return (Criteria) this;
        }

        public Criteria andSjymcNotEqualTo(String value) {
            addCriterion("sjymc <>", value, "sjymc");
            return (Criteria) this;
        }

        public Criteria andSjymcGreaterThan(String value) {
            addCriterion("sjymc >", value, "sjymc");
            return (Criteria) this;
        }

        public Criteria andSjymcGreaterThanOrEqualTo(String value) {
            addCriterion("sjymc >=", value, "sjymc");
            return (Criteria) this;
        }

        public Criteria andSjymcLessThan(String value) {
            addCriterion("sjymc <", value, "sjymc");
            return (Criteria) this;
        }

        public Criteria andSjymcLessThanOrEqualTo(String value) {
            addCriterion("sjymc <=", value, "sjymc");
            return (Criteria) this;
        }

        public Criteria andSjymcLike(String value) {
            addCriterion("sjymc like", value, "sjymc");
            return (Criteria) this;
        }

        public Criteria andSjymcNotLike(String value) {
            addCriterion("sjymc not like", value, "sjymc");
            return (Criteria) this;
        }

        public Criteria andSjymcIn(List<String> values) {
            addCriterion("sjymc in", values, "sjymc");
            return (Criteria) this;
        }

        public Criteria andSjymcNotIn(List<String> values) {
            addCriterion("sjymc not in", values, "sjymc");
            return (Criteria) this;
        }

        public Criteria andSjymcBetween(String value1, String value2) {
            addCriterion("sjymc between", value1, value2, "sjymc");
            return (Criteria) this;
        }

        public Criteria andSjymcNotBetween(String value1, String value2) {
            addCriterion("sjymc not between", value1, value2, "sjymc");
            return (Criteria) this;
        }

        public Criteria andFlbmIsNull() {
            addCriterion("flbm is null");
            return (Criteria) this;
        }

        public Criteria andFlbmIsNotNull() {
            addCriterion("flbm is not null");
            return (Criteria) this;
        }

        public Criteria andFlbmEqualTo(String value) {
            addCriterion("flbm =", value, "flbm");
            return (Criteria) this;
        }

        public Criteria andFlbmNotEqualTo(String value) {
            addCriterion("flbm <>", value, "flbm");
            return (Criteria) this;
        }

        public Criteria andFlbmGreaterThan(String value) {
            addCriterion("flbm >", value, "flbm");
            return (Criteria) this;
        }

        public Criteria andFlbmGreaterThanOrEqualTo(String value) {
            addCriterion("flbm >=", value, "flbm");
            return (Criteria) this;
        }

        public Criteria andFlbmLessThan(String value) {
            addCriterion("flbm <", value, "flbm");
            return (Criteria) this;
        }

        public Criteria andFlbmLessThanOrEqualTo(String value) {
            addCriterion("flbm <=", value, "flbm");
            return (Criteria) this;
        }

        public Criteria andFlbmLike(String value) {
            addCriterion("flbm like", value, "flbm");
            return (Criteria) this;
        }

        public Criteria andFlbmNotLike(String value) {
            addCriterion("flbm not like", value, "flbm");
            return (Criteria) this;
        }

        public Criteria andFlbmIn(List<String> values) {
            addCriterion("flbm in", values, "flbm");
            return (Criteria) this;
        }

        public Criteria andFlbmNotIn(List<String> values) {
            addCriterion("flbm not in", values, "flbm");
            return (Criteria) this;
        }

        public Criteria andFlbmBetween(String value1, String value2) {
            addCriterion("flbm between", value1, value2, "flbm");
            return (Criteria) this;
        }

        public Criteria andFlbmNotBetween(String value1, String value2) {
            addCriterion("flbm not between", value1, value2, "flbm");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("bz is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("bz is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("bz =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("bz <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("bz >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("bz >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("bz <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("bz <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("bz like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("bz not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("bz in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("bz not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("bz between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("bz not between", value1, value2, "bz");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xtpz_sjy
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xtpz_sjy
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}