package cn.com.gxbolian.databank.entity;

import java.util.Date;

public class XtpzCxfa {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_cxfa.lsh
	 * @mbg.generated
	 */
	private String lsh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_cxfa.sjybm
	 * @mbg.generated
	 */
	private String sjybm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_cxfa.mc
	 * @mbg.generated
	 */
	private String mc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_cxfa.ms
	 * @mbg.generated
	 */
	private String ms;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_cxfa.cxzd
	 * @mbg.generated
	 */
	private String cxzd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_cxfa.sxzd
	 * @mbg.generated
	 */
	private String sxzd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_cxfa.sxsz
	 * @mbg.generated
	 */
	private String sxsz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_cxfa.gjsx
	 * @mbg.generated
	 */
	private String gjsx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_cxfa.czybm
	 * @mbg.generated
	 */
	private String czybm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_cxfa.cjsj
	 * @mbg.generated
	 */
	private Date cjsj;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_cxfa.lsh
	 * @return  the value of xtpz_cxfa.lsh
	 * @mbg.generated
	 */
	public String getLsh() {
		return lsh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_cxfa.lsh
	 * @param lsh  the value for xtpz_cxfa.lsh
	 * @mbg.generated
	 */
	public void setLsh(String lsh) {
		this.lsh = lsh == null ? null : lsh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_cxfa.sjybm
	 * @return  the value of xtpz_cxfa.sjybm
	 * @mbg.generated
	 */
	public String getSjybm() {
		return sjybm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_cxfa.sjybm
	 * @param sjybm  the value for xtpz_cxfa.sjybm
	 * @mbg.generated
	 */
	public void setSjybm(String sjybm) {
		this.sjybm = sjybm == null ? null : sjybm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_cxfa.mc
	 * @return  the value of xtpz_cxfa.mc
	 * @mbg.generated
	 */
	public String getMc() {
		return mc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_cxfa.mc
	 * @param mc  the value for xtpz_cxfa.mc
	 * @mbg.generated
	 */
	public void setMc(String mc) {
		this.mc = mc == null ? null : mc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_cxfa.ms
	 * @return  the value of xtpz_cxfa.ms
	 * @mbg.generated
	 */
	public String getMs() {
		return ms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_cxfa.ms
	 * @param ms  the value for xtpz_cxfa.ms
	 * @mbg.generated
	 */
	public void setMs(String ms) {
		this.ms = ms == null ? null : ms.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_cxfa.cxzd
	 * @return  the value of xtpz_cxfa.cxzd
	 * @mbg.generated
	 */
	public String getCxzd() {
		return cxzd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_cxfa.cxzd
	 * @param cxzd  the value for xtpz_cxfa.cxzd
	 * @mbg.generated
	 */
	public void setCxzd(String cxzd) {
		this.cxzd = cxzd == null ? null : cxzd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_cxfa.sxzd
	 * @return  the value of xtpz_cxfa.sxzd
	 * @mbg.generated
	 */
	public String getSxzd() {
		return sxzd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_cxfa.sxzd
	 * @param sxzd  the value for xtpz_cxfa.sxzd
	 * @mbg.generated
	 */
	public void setSxzd(String sxzd) {
		this.sxzd = sxzd == null ? null : sxzd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_cxfa.sxsz
	 * @return  the value of xtpz_cxfa.sxsz
	 * @mbg.generated
	 */
	public String getSxsz() {
		return sxsz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_cxfa.sxsz
	 * @param sxsz  the value for xtpz_cxfa.sxsz
	 * @mbg.generated
	 */
	public void setSxsz(String sxsz) {
		this.sxsz = sxsz == null ? null : sxsz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_cxfa.gjsx
	 * @return  the value of xtpz_cxfa.gjsx
	 * @mbg.generated
	 */
	public String getGjsx() {
		return gjsx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_cxfa.gjsx
	 * @param gjsx  the value for xtpz_cxfa.gjsx
	 * @mbg.generated
	 */
	public void setGjsx(String gjsx) {
		this.gjsx = gjsx == null ? null : gjsx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_cxfa.czybm
	 * @return  the value of xtpz_cxfa.czybm
	 * @mbg.generated
	 */
	public String getCzybm() {
		return czybm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_cxfa.czybm
	 * @param czybm  the value for xtpz_cxfa.czybm
	 * @mbg.generated
	 */
	public void setCzybm(String czybm) {
		this.czybm = czybm == null ? null : czybm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_cxfa.cjsj
	 * @return  the value of xtpz_cxfa.cjsj
	 * @mbg.generated
	 */
	public Date getCjsj() {
		return cjsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_cxfa.cjsj
	 * @param cjsj  the value for xtpz_cxfa.cjsj
	 * @mbg.generated
	 */
	public void setCjsj(Date cjsj) {
		this.cjsj = cjsj;
	}
}