package cn.com.gxbolian.databank.entity;

import java.util.ArrayList;
import java.util.List;

public class XtpzBzhzjpzGlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    public XtpzBzhzjpzGlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLshIsNull() {
            addCriterion("lsh is null");
            return (Criteria) this;
        }

        public Criteria andLshIsNotNull() {
            addCriterion("lsh is not null");
            return (Criteria) this;
        }

        public Criteria andLshEqualTo(String value) {
            addCriterion("lsh =", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshNotEqualTo(String value) {
            addCriterion("lsh <>", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshGreaterThan(String value) {
            addCriterion("lsh >", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshGreaterThanOrEqualTo(String value) {
            addCriterion("lsh >=", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshLessThan(String value) {
            addCriterion("lsh <", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshLessThanOrEqualTo(String value) {
            addCriterion("lsh <=", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshLike(String value) {
            addCriterion("lsh like", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshNotLike(String value) {
            addCriterion("lsh not like", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshIn(List<String> values) {
            addCriterion("lsh in", values, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshNotIn(List<String> values) {
            addCriterion("lsh not in", values, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshBetween(String value1, String value2) {
            addCriterion("lsh between", value1, value2, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshNotBetween(String value1, String value2) {
            addCriterion("lsh not between", value1, value2, "lsh");
            return (Criteria) this;
        }

        public Criteria andBzhlshIsNull() {
            addCriterion("bzhlsh is null");
            return (Criteria) this;
        }

        public Criteria andBzhlshIsNotNull() {
            addCriterion("bzhlsh is not null");
            return (Criteria) this;
        }

        public Criteria andBzhlshEqualTo(String value) {
            addCriterion("bzhlsh =", value, "bzhlsh");
            return (Criteria) this;
        }

        public Criteria andBzhlshNotEqualTo(String value) {
            addCriterion("bzhlsh <>", value, "bzhlsh");
            return (Criteria) this;
        }

        public Criteria andBzhlshGreaterThan(String value) {
            addCriterion("bzhlsh >", value, "bzhlsh");
            return (Criteria) this;
        }

        public Criteria andBzhlshGreaterThanOrEqualTo(String value) {
            addCriterion("bzhlsh >=", value, "bzhlsh");
            return (Criteria) this;
        }

        public Criteria andBzhlshLessThan(String value) {
            addCriterion("bzhlsh <", value, "bzhlsh");
            return (Criteria) this;
        }

        public Criteria andBzhlshLessThanOrEqualTo(String value) {
            addCriterion("bzhlsh <=", value, "bzhlsh");
            return (Criteria) this;
        }

        public Criteria andBzhlshLike(String value) {
            addCriterion("bzhlsh like", value, "bzhlsh");
            return (Criteria) this;
        }

        public Criteria andBzhlshNotLike(String value) {
            addCriterion("bzhlsh not like", value, "bzhlsh");
            return (Criteria) this;
        }

        public Criteria andBzhlshIn(List<String> values) {
            addCriterion("bzhlsh in", values, "bzhlsh");
            return (Criteria) this;
        }

        public Criteria andBzhlshNotIn(List<String> values) {
            addCriterion("bzhlsh not in", values, "bzhlsh");
            return (Criteria) this;
        }

        public Criteria andBzhlshBetween(String value1, String value2) {
            addCriterion("bzhlsh between", value1, value2, "bzhlsh");
            return (Criteria) this;
        }

        public Criteria andBzhlshNotBetween(String value1, String value2) {
            addCriterion("bzhlsh not between", value1, value2, "bzhlsh");
            return (Criteria) this;
        }

        public Criteria andZdmcIsNull() {
            addCriterion("zdmc is null");
            return (Criteria) this;
        }

        public Criteria andZdmcIsNotNull() {
            addCriterion("zdmc is not null");
            return (Criteria) this;
        }

        public Criteria andZdmcEqualTo(String value) {
            addCriterion("zdmc =", value, "zdmc");
            return (Criteria) this;
        }

        public Criteria andZdmcNotEqualTo(String value) {
            addCriterion("zdmc <>", value, "zdmc");
            return (Criteria) this;
        }

        public Criteria andZdmcGreaterThan(String value) {
            addCriterion("zdmc >", value, "zdmc");
            return (Criteria) this;
        }

        public Criteria andZdmcGreaterThanOrEqualTo(String value) {
            addCriterion("zdmc >=", value, "zdmc");
            return (Criteria) this;
        }

        public Criteria andZdmcLessThan(String value) {
            addCriterion("zdmc <", value, "zdmc");
            return (Criteria) this;
        }

        public Criteria andZdmcLessThanOrEqualTo(String value) {
            addCriterion("zdmc <=", value, "zdmc");
            return (Criteria) this;
        }

        public Criteria andZdmcLike(String value) {
            addCriterion("zdmc like", value, "zdmc");
            return (Criteria) this;
        }

        public Criteria andZdmcNotLike(String value) {
            addCriterion("zdmc not like", value, "zdmc");
            return (Criteria) this;
        }

        public Criteria andZdmcIn(List<String> values) {
            addCriterion("zdmc in", values, "zdmc");
            return (Criteria) this;
        }

        public Criteria andZdmcNotIn(List<String> values) {
            addCriterion("zdmc not in", values, "zdmc");
            return (Criteria) this;
        }

        public Criteria andZdmcBetween(String value1, String value2) {
            addCriterion("zdmc between", value1, value2, "zdmc");
            return (Criteria) this;
        }

        public Criteria andZdmcNotBetween(String value1, String value2) {
            addCriterion("zdmc not between", value1, value2, "zdmc");
            return (Criteria) this;
        }

        public Criteria andGlsjbIsNull() {
            addCriterion("glsjb is null");
            return (Criteria) this;
        }

        public Criteria andGlsjbIsNotNull() {
            addCriterion("glsjb is not null");
            return (Criteria) this;
        }

        public Criteria andGlsjbEqualTo(String value) {
            addCriterion("glsjb =", value, "glsjb");
            return (Criteria) this;
        }

        public Criteria andGlsjbNotEqualTo(String value) {
            addCriterion("glsjb <>", value, "glsjb");
            return (Criteria) this;
        }

        public Criteria andGlsjbGreaterThan(String value) {
            addCriterion("glsjb >", value, "glsjb");
            return (Criteria) this;
        }

        public Criteria andGlsjbGreaterThanOrEqualTo(String value) {
            addCriterion("glsjb >=", value, "glsjb");
            return (Criteria) this;
        }

        public Criteria andGlsjbLessThan(String value) {
            addCriterion("glsjb <", value, "glsjb");
            return (Criteria) this;
        }

        public Criteria andGlsjbLessThanOrEqualTo(String value) {
            addCriterion("glsjb <=", value, "glsjb");
            return (Criteria) this;
        }

        public Criteria andGlsjbLike(String value) {
            addCriterion("glsjb like", value, "glsjb");
            return (Criteria) this;
        }

        public Criteria andGlsjbNotLike(String value) {
            addCriterion("glsjb not like", value, "glsjb");
            return (Criteria) this;
        }

        public Criteria andGlsjbIn(List<String> values) {
            addCriterion("glsjb in", values, "glsjb");
            return (Criteria) this;
        }

        public Criteria andGlsjbNotIn(List<String> values) {
            addCriterion("glsjb not in", values, "glsjb");
            return (Criteria) this;
        }

        public Criteria andGlsjbBetween(String value1, String value2) {
            addCriterion("glsjb between", value1, value2, "glsjb");
            return (Criteria) this;
        }

        public Criteria andGlsjbNotBetween(String value1, String value2) {
            addCriterion("glsjb not between", value1, value2, "glsjb");
            return (Criteria) this;
        }

        public Criteria andGlzdIsNull() {
            addCriterion("glzd is null");
            return (Criteria) this;
        }

        public Criteria andGlzdIsNotNull() {
            addCriterion("glzd is not null");
            return (Criteria) this;
        }

        public Criteria andGlzdEqualTo(String value) {
            addCriterion("glzd =", value, "glzd");
            return (Criteria) this;
        }

        public Criteria andGlzdNotEqualTo(String value) {
            addCriterion("glzd <>", value, "glzd");
            return (Criteria) this;
        }

        public Criteria andGlzdGreaterThan(String value) {
            addCriterion("glzd >", value, "glzd");
            return (Criteria) this;
        }

        public Criteria andGlzdGreaterThanOrEqualTo(String value) {
            addCriterion("glzd >=", value, "glzd");
            return (Criteria) this;
        }

        public Criteria andGlzdLessThan(String value) {
            addCriterion("glzd <", value, "glzd");
            return (Criteria) this;
        }

        public Criteria andGlzdLessThanOrEqualTo(String value) {
            addCriterion("glzd <=", value, "glzd");
            return (Criteria) this;
        }

        public Criteria andGlzdLike(String value) {
            addCriterion("glzd like", value, "glzd");
            return (Criteria) this;
        }

        public Criteria andGlzdNotLike(String value) {
            addCriterion("glzd not like", value, "glzd");
            return (Criteria) this;
        }

        public Criteria andGlzdIn(List<String> values) {
            addCriterion("glzd in", values, "glzd");
            return (Criteria) this;
        }

        public Criteria andGlzdNotIn(List<String> values) {
            addCriterion("glzd not in", values, "glzd");
            return (Criteria) this;
        }

        public Criteria andGlzdBetween(String value1, String value2) {
            addCriterion("glzd between", value1, value2, "glzd");
            return (Criteria) this;
        }

        public Criteria andGlzdNotBetween(String value1, String value2) {
            addCriterion("glzd not between", value1, value2, "glzd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}