package cn.com.gxbolian.databank.entity;

public class XtpzBzhzjpz {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz.lsh
	 * @mbg.generated
	 */
	private String lsh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz.sjybm
	 * @mbg.generated
	 */
	private String sjybm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz.mc
	 * @mbg.generated
	 */
	private String mc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz.ms
	 * @mbg.generated
	 */
	private String ms;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz.jb
	 * @mbg.generated
	 */
	private String jb;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz.lsh
	 * @return  the value of xtpz_bzhzjpz.lsh
	 * @mbg.generated
	 */
	public String getLsh() {
		return lsh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz.lsh
	 * @param lsh  the value for xtpz_bzhzjpz.lsh
	 * @mbg.generated
	 */
	public void setLsh(String lsh) {
		this.lsh = lsh == null ? null : lsh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz.sjybm
	 * @return  the value of xtpz_bzhzjpz.sjybm
	 * @mbg.generated
	 */
	public String getSjybm() {
		return sjybm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz.sjybm
	 * @param sjybm  the value for xtpz_bzhzjpz.sjybm
	 * @mbg.generated
	 */
	public void setSjybm(String sjybm) {
		this.sjybm = sjybm == null ? null : sjybm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz.mc
	 * @return  the value of xtpz_bzhzjpz.mc
	 * @mbg.generated
	 */
	public String getMc() {
		return mc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz.mc
	 * @param mc  the value for xtpz_bzhzjpz.mc
	 * @mbg.generated
	 */
	public void setMc(String mc) {
		this.mc = mc == null ? null : mc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz.ms
	 * @return  the value of xtpz_bzhzjpz.ms
	 * @mbg.generated
	 */
	public String getMs() {
		return ms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz.ms
	 * @param ms  the value for xtpz_bzhzjpz.ms
	 * @mbg.generated
	 */
	public void setMs(String ms) {
		this.ms = ms == null ? null : ms.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz.jb
	 * @return  the value of xtpz_bzhzjpz.jb
	 * @mbg.generated
	 */
	public String getJb() {
		return jb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz.jb
	 * @param jb  the value for xtpz_bzhzjpz.jb
	 * @mbg.generated
	 */
	public void setJb(String jb) {
		this.jb = jb == null ? null : jb.trim();
	}
}