package cn.com.gxbolian.databank.entity;

import java.io.Serializable;

public class XtpzSjzd  implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjzd.zdbm
	 * 
	 * @mbg.generated
	 */
	private String zdbm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjzd.sjybm
	 * 
	 * @mbg.generated
	 */
	private String sjybm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjzd.zdmc
	 * 
	 * @mbg.generated
	 */
	private String zdmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjzd.ybmc
	 * 
	 * @mbg.generated
	 */
	private String ybmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjzd.ybzd
	 * 
	 * @mbg.generated
	 */
	private String ybzd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjzd.sjlx
	 * 
	 * @mbg.generated
	 */
	private String sjlx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjzd.jhbz
	 * 
	 * @mbg.generated
	 */
	private String jhbz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjzd.xlzdbm
	 * 
	 * @mbg.generated
	 */
	private String xlzdbm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjzd.zjbz
	 * 
	 * @mbg.generated
	 */
	private String zjbz;

	private boolean pnode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjzd.zdbm
	 * 
	 * @return the value of xtpz_sjzd.zdbm
	 * @mbg.generated
	 */
	public String getZdbm() {
		return zdbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjzd.zdbm
	 * 
	 * @param zdbm
	 *            the value for xtpz_sjzd.zdbm
	 * @mbg.generated
	 */
	public void setZdbm(String zdbm) {
		this.zdbm = zdbm == null ? null : zdbm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjzd.sjybm
	 * 
	 * @return the value of xtpz_sjzd.sjybm
	 * @mbg.generated
	 */
	public String getSjybm() {
		return sjybm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjzd.sjybm
	 * 
	 * @param sjybm
	 *            the value for xtpz_sjzd.sjybm
	 * @mbg.generated
	 */
	public void setSjybm(String sjybm) {
		this.sjybm = sjybm == null ? null : sjybm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjzd.zdmc
	 * 
	 * @return the value of xtpz_sjzd.zdmc
	 * @mbg.generated
	 */
	public String getZdmc() {
		return zdmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjzd.zdmc
	 * 
	 * @param zdmc
	 *            the value for xtpz_sjzd.zdmc
	 * @mbg.generated
	 */
	public void setZdmc(String zdmc) {
		this.zdmc = zdmc == null ? null : zdmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjzd.ybmc
	 * 
	 * @return the value of xtpz_sjzd.ybmc
	 * @mbg.generated
	 */
	public String getYbmc() {
		return ybmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjzd.ybmc
	 * 
	 * @param ybmc
	 *            the value for xtpz_sjzd.ybmc
	 * @mbg.generated
	 */
	public void setYbmc(String ybmc) {
		this.ybmc = ybmc == null ? null : ybmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjzd.ybzd
	 * 
	 * @return the value of xtpz_sjzd.ybzd
	 * @mbg.generated
	 */
	public String getYbzd() {
		return ybzd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjzd.ybzd
	 * 
	 * @param ybzd
	 *            the value for xtpz_sjzd.ybzd
	 * @mbg.generated
	 */
	public void setYbzd(String ybzd) {
		this.ybzd = ybzd == null ? null : ybzd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjzd.sjlx
	 * 
	 * @return the value of xtpz_sjzd.sjlx
	 * @mbg.generated
	 */
	public String getSjlx() {
		return sjlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjzd.sjlx
	 * 
	 * @param sjlx
	 *            the value for xtpz_sjzd.sjlx
	 * @mbg.generated
	 */
	public void setSjlx(String sjlx) {
		this.sjlx = sjlx == null ? null : sjlx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjzd.jhbz
	 * 
	 * @return the value of xtpz_sjzd.jhbz
	 * @mbg.generated
	 */
	public String getJhbz() {
		return jhbz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjzd.jhbz
	 * 
	 * @param jhbz
	 *            the value for xtpz_sjzd.jhbz
	 * @mbg.generated
	 */
	public void setJhbz(String jhbz) {
		this.jhbz = jhbz == null ? null : jhbz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjzd.xlzdbm
	 * 
	 * @return the value of xtpz_sjzd.xlzdbm
	 * @mbg.generated
	 */
	public String getXlzdbm() {
		return xlzdbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjzd.xlzdbm
	 * 
	 * @param xlzdbm
	 *            the value for xtpz_sjzd.xlzdbm
	 * @mbg.generated
	 */
	public void setXlzdbm(String xlzdbm) {
		this.xlzdbm = xlzdbm == null ? null : xlzdbm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjzd.zjbz
	 * 
	 * @return the value of xtpz_sjzd.zjbz
	 * @mbg.generated
	 */
	public String getZjbz() {
		return zjbz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjzd.zjbz
	 * 
	 * @param zjbz
	 *            the value for xtpz_sjzd.zjbz
	 * @mbg.generated
	 */
	public void setZjbz(String zjbz) {
		this.zjbz = zjbz == null ? null : zjbz.trim();
	}

	public boolean isPnode() {
		return pnode;
	}

	public void setPnode(boolean pnode) {
		this.pnode = pnode;
	}

}