package cn.com.gxbolian.databank.entity;

public class XtpzSjglys {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjglys.lsh
     *
     * @mbg.generated
     */
    private String lsh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjglys.ybmca
     *
     * @mbg.generated
     */
    private String ybmca;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjglys.ybzda
     *
     * @mbg.generated
     */
    private String ybzda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjglys.ybmcb
     *
     * @mbg.generated
     */
    private String ybmcb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjglys.ybzdb
     *
     * @mbg.generated
     */
    private String ybzdb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjglys.lsh
     *
     * @return the value of xtpz_sjglys.lsh
     *
     * @mbg.generated
     */
    public String getLsh() {
        return lsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjglys.lsh
     *
     * @param lsh the value for xtpz_sjglys.lsh
     *
     * @mbg.generated
     */
    public void setLsh(String lsh) {
        this.lsh = lsh == null ? null : lsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjglys.ybmca
     *
     * @return the value of xtpz_sjglys.ybmca
     *
     * @mbg.generated
     */
    public String getYbmca() {
        return ybmca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjglys.ybmca
     *
     * @param ybmca the value for xtpz_sjglys.ybmca
     *
     * @mbg.generated
     */
    public void setYbmca(String ybmca) {
        this.ybmca = ybmca == null ? null : ybmca.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjglys.ybzda
     *
     * @return the value of xtpz_sjglys.ybzda
     *
     * @mbg.generated
     */
    public String getYbzda() {
        return ybzda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjglys.ybzda
     *
     * @param ybzda the value for xtpz_sjglys.ybzda
     *
     * @mbg.generated
     */
    public void setYbzda(String ybzda) {
        this.ybzda = ybzda == null ? null : ybzda.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjglys.ybmcb
     *
     * @return the value of xtpz_sjglys.ybmcb
     *
     * @mbg.generated
     */
    public String getYbmcb() {
        return ybmcb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjglys.ybmcb
     *
     * @param ybmcb the value for xtpz_sjglys.ybmcb
     *
     * @mbg.generated
     */
    public void setYbmcb(String ybmcb) {
        this.ybmcb = ybmcb == null ? null : ybmcb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjglys.ybzdb
     *
     * @return the value of xtpz_sjglys.ybzdb
     *
     * @mbg.generated
     */
    public String getYbzdb() {
        return ybzdb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjglys.ybzdb
     *
     * @param ybzdb the value for xtpz_sjglys.ybzdb
     *
     * @mbg.generated
     */
    public void setYbzdb(String ybzdb) {
        this.ybzdb = ybzdb == null ? null : ybzdb.trim();
    }
}