package cn.com.gxbolian.databank.entity;

import java.util.ArrayList;
import java.util.List;

public class XtpzBzhzjpzExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	public XtpzBzhzjpzExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andLshIsNull() {
			addCriterion("lsh is null");
			return (Criteria) this;
		}

		public Criteria andLshIsNotNull() {
			addCriterion("lsh is not null");
			return (Criteria) this;
		}

		public Criteria andLshEqualTo(String value) {
			addCriterion("lsh =", value, "lsh");
			return (Criteria) this;
		}

		public Criteria andLshNotEqualTo(String value) {
			addCriterion("lsh <>", value, "lsh");
			return (Criteria) this;
		}

		public Criteria andLshGreaterThan(String value) {
			addCriterion("lsh >", value, "lsh");
			return (Criteria) this;
		}

		public Criteria andLshGreaterThanOrEqualTo(String value) {
			addCriterion("lsh >=", value, "lsh");
			return (Criteria) this;
		}

		public Criteria andLshLessThan(String value) {
			addCriterion("lsh <", value, "lsh");
			return (Criteria) this;
		}

		public Criteria andLshLessThanOrEqualTo(String value) {
			addCriterion("lsh <=", value, "lsh");
			return (Criteria) this;
		}

		public Criteria andLshLike(String value) {
			addCriterion("lsh like", value, "lsh");
			return (Criteria) this;
		}

		public Criteria andLshNotLike(String value) {
			addCriterion("lsh not like", value, "lsh");
			return (Criteria) this;
		}

		public Criteria andLshIn(List<String> values) {
			addCriterion("lsh in", values, "lsh");
			return (Criteria) this;
		}

		public Criteria andLshNotIn(List<String> values) {
			addCriterion("lsh not in", values, "lsh");
			return (Criteria) this;
		}

		public Criteria andLshBetween(String value1, String value2) {
			addCriterion("lsh between", value1, value2, "lsh");
			return (Criteria) this;
		}

		public Criteria andLshNotBetween(String value1, String value2) {
			addCriterion("lsh not between", value1, value2, "lsh");
			return (Criteria) this;
		}

		public Criteria andSjybmIsNull() {
			addCriterion("sjybm is null");
			return (Criteria) this;
		}

		public Criteria andSjybmIsNotNull() {
			addCriterion("sjybm is not null");
			return (Criteria) this;
		}

		public Criteria andSjybmEqualTo(String value) {
			addCriterion("sjybm =", value, "sjybm");
			return (Criteria) this;
		}

		public Criteria andSjybmNotEqualTo(String value) {
			addCriterion("sjybm <>", value, "sjybm");
			return (Criteria) this;
		}

		public Criteria andSjybmGreaterThan(String value) {
			addCriterion("sjybm >", value, "sjybm");
			return (Criteria) this;
		}

		public Criteria andSjybmGreaterThanOrEqualTo(String value) {
			addCriterion("sjybm >=", value, "sjybm");
			return (Criteria) this;
		}

		public Criteria andSjybmLessThan(String value) {
			addCriterion("sjybm <", value, "sjybm");
			return (Criteria) this;
		}

		public Criteria andSjybmLessThanOrEqualTo(String value) {
			addCriterion("sjybm <=", value, "sjybm");
			return (Criteria) this;
		}

		public Criteria andSjybmLike(String value) {
			addCriterion("sjybm like", value, "sjybm");
			return (Criteria) this;
		}

		public Criteria andSjybmNotLike(String value) {
			addCriterion("sjybm not like", value, "sjybm");
			return (Criteria) this;
		}

		public Criteria andSjybmIn(List<String> values) {
			addCriterion("sjybm in", values, "sjybm");
			return (Criteria) this;
		}

		public Criteria andSjybmNotIn(List<String> values) {
			addCriterion("sjybm not in", values, "sjybm");
			return (Criteria) this;
		}

		public Criteria andSjybmBetween(String value1, String value2) {
			addCriterion("sjybm between", value1, value2, "sjybm");
			return (Criteria) this;
		}

		public Criteria andSjybmNotBetween(String value1, String value2) {
			addCriterion("sjybm not between", value1, value2, "sjybm");
			return (Criteria) this;
		}

		public Criteria andMcIsNull() {
			addCriterion("mc is null");
			return (Criteria) this;
		}

		public Criteria andMcIsNotNull() {
			addCriterion("mc is not null");
			return (Criteria) this;
		}

		public Criteria andMcEqualTo(String value) {
			addCriterion("mc =", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcNotEqualTo(String value) {
			addCriterion("mc <>", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcGreaterThan(String value) {
			addCriterion("mc >", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcGreaterThanOrEqualTo(String value) {
			addCriterion("mc >=", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcLessThan(String value) {
			addCriterion("mc <", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcLessThanOrEqualTo(String value) {
			addCriterion("mc <=", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcLike(String value) {
			addCriterion("mc like", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcNotLike(String value) {
			addCriterion("mc not like", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcIn(List<String> values) {
			addCriterion("mc in", values, "mc");
			return (Criteria) this;
		}

		public Criteria andMcNotIn(List<String> values) {
			addCriterion("mc not in", values, "mc");
			return (Criteria) this;
		}

		public Criteria andMcBetween(String value1, String value2) {
			addCriterion("mc between", value1, value2, "mc");
			return (Criteria) this;
		}

		public Criteria andMcNotBetween(String value1, String value2) {
			addCriterion("mc not between", value1, value2, "mc");
			return (Criteria) this;
		}

		public Criteria andMsIsNull() {
			addCriterion("ms is null");
			return (Criteria) this;
		}

		public Criteria andMsIsNotNull() {
			addCriterion("ms is not null");
			return (Criteria) this;
		}

		public Criteria andMsEqualTo(String value) {
			addCriterion("ms =", value, "ms");
			return (Criteria) this;
		}

		public Criteria andMsNotEqualTo(String value) {
			addCriterion("ms <>", value, "ms");
			return (Criteria) this;
		}

		public Criteria andMsGreaterThan(String value) {
			addCriterion("ms >", value, "ms");
			return (Criteria) this;
		}

		public Criteria andMsGreaterThanOrEqualTo(String value) {
			addCriterion("ms >=", value, "ms");
			return (Criteria) this;
		}

		public Criteria andMsLessThan(String value) {
			addCriterion("ms <", value, "ms");
			return (Criteria) this;
		}

		public Criteria andMsLessThanOrEqualTo(String value) {
			addCriterion("ms <=", value, "ms");
			return (Criteria) this;
		}

		public Criteria andMsLike(String value) {
			addCriterion("ms like", value, "ms");
			return (Criteria) this;
		}

		public Criteria andMsNotLike(String value) {
			addCriterion("ms not like", value, "ms");
			return (Criteria) this;
		}

		public Criteria andMsIn(List<String> values) {
			addCriterion("ms in", values, "ms");
			return (Criteria) this;
		}

		public Criteria andMsNotIn(List<String> values) {
			addCriterion("ms not in", values, "ms");
			return (Criteria) this;
		}

		public Criteria andMsBetween(String value1, String value2) {
			addCriterion("ms between", value1, value2, "ms");
			return (Criteria) this;
		}

		public Criteria andMsNotBetween(String value1, String value2) {
			addCriterion("ms not between", value1, value2, "ms");
			return (Criteria) this;
		}

		public Criteria andJbIsNull() {
			addCriterion("jb is null");
			return (Criteria) this;
		}

		public Criteria andJbIsNotNull() {
			addCriterion("jb is not null");
			return (Criteria) this;
		}

		public Criteria andJbEqualTo(String value) {
			addCriterion("jb =", value, "jb");
			return (Criteria) this;
		}

		public Criteria andJbNotEqualTo(String value) {
			addCriterion("jb <>", value, "jb");
			return (Criteria) this;
		}

		public Criteria andJbGreaterThan(String value) {
			addCriterion("jb >", value, "jb");
			return (Criteria) this;
		}

		public Criteria andJbGreaterThanOrEqualTo(String value) {
			addCriterion("jb >=", value, "jb");
			return (Criteria) this;
		}

		public Criteria andJbLessThan(String value) {
			addCriterion("jb <", value, "jb");
			return (Criteria) this;
		}

		public Criteria andJbLessThanOrEqualTo(String value) {
			addCriterion("jb <=", value, "jb");
			return (Criteria) this;
		}

		public Criteria andJbLike(String value) {
			addCriterion("jb like", value, "jb");
			return (Criteria) this;
		}

		public Criteria andJbNotLike(String value) {
			addCriterion("jb not like", value, "jb");
			return (Criteria) this;
		}

		public Criteria andJbIn(List<String> values) {
			addCriterion("jb in", values, "jb");
			return (Criteria) this;
		}

		public Criteria andJbNotIn(List<String> values) {
			addCriterion("jb not in", values, "jb");
			return (Criteria) this;
		}

		public Criteria andJbBetween(String value1, String value2) {
			addCriterion("jb between", value1, value2, "jb");
			return (Criteria) this;
		}

		public Criteria andJbNotBetween(String value1, String value2) {
			addCriterion("jb not between", value1, value2, "jb");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table xtpz_bzhzjpz
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xtpz_bzhzjpz
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}