package cn.com.gxbolian.databank.entity;

import java.util.ArrayList;
import java.util.List;

public class XtpzSjy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjy.sjybm
	 * 
	 * @mbg.generated
	 */
	private String sjybm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjy.sjymc
	 * 
	 * @mbg.generated
	 */
	private String sjymc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjy.flbm
	 * 
	 * @mbg.generated
	 */
	private String flbm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xtpz_sjy.bz
	 * 
	 * @mbg.generated
	 */
	private String bz;

	private List<XtpzSjy> nodes = new ArrayList<XtpzSjy>();

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjy.sjybm
	 * 
	 * @return the value of xtpz_sjy.sjybm
	 * @mbg.generated
	 */
	public String getSjybm() {
		return sjybm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjy.sjybm
	 * 
	 * @param sjybm
	 *            the value for xtpz_sjy.sjybm
	 * @mbg.generated
	 */
	public void setSjybm(String sjybm) {
		this.sjybm = sjybm == null ? null : sjybm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjy.sjymc
	 * 
	 * @return the value of xtpz_sjy.sjymc
	 * @mbg.generated
	 */
	public String getSjymc() {
		return sjymc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjy.sjymc
	 * 
	 * @param sjymc
	 *            the value for xtpz_sjy.sjymc
	 * @mbg.generated
	 */
	public void setSjymc(String sjymc) {
		this.sjymc = sjymc == null ? null : sjymc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjy.flbm
	 * 
	 * @return the value of xtpz_sjy.flbm
	 * @mbg.generated
	 */
	public String getFlbm() {
		return flbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjy.flbm
	 * 
	 * @param flbm
	 *            the value for xtpz_sjy.flbm
	 * @mbg.generated
	 */
	public void setFlbm(String flbm) {
		this.flbm = flbm == null ? null : flbm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xtpz_sjy.bz
	 * 
	 * @return the value of xtpz_sjy.bz
	 * @mbg.generated
	 */
	public String getBz() {
		return bz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xtpz_sjy.bz
	 * 
	 * @param bz
	 *            the value for xtpz_sjy.bz
	 * @mbg.generated
	 */
	public void setBz(String bz) {
		this.bz = bz == null ? null : bz.trim();
	}

	public List<XtpzSjy> getNodes() {
		return nodes;
	}

	public void setNodes(List<XtpzSjy> nodes) {
		this.nodes = nodes;
	}

}