package cn.com.gxbolian.databank.entity;

import java.io.Serializable;

public class XtpzBzhzjpzGl  implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_bzhzjpz_gl.lsh
     *
     * @mbg.generated
     */
    private String lsh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_bzhzjpz_gl.bzhlsh
     *
     * @mbg.generated
     */
    private String bzhlsh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_bzhzjpz_gl.zdmc
     *
     * @mbg.generated
     */
    private String zdmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_bzhzjpz_gl.glsjb
     *
     * @mbg.generated
     */
    private String glsjb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_bzhzjpz_gl.glzd
     *
     * @mbg.generated
     */
    private String glzd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_bzhzjpz_gl.lsh
     *
     * @return the value of xtpz_bzhzjpz_gl.lsh
     *
     * @mbg.generated
     */
    public String getLsh() {
        return lsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_bzhzjpz_gl.lsh
     *
     * @param lsh the value for xtpz_bzhzjpz_gl.lsh
     *
     * @mbg.generated
     */
    public void setLsh(String lsh) {
        this.lsh = lsh == null ? null : lsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_bzhzjpz_gl.bzhlsh
     *
     * @return the value of xtpz_bzhzjpz_gl.bzhlsh
     *
     * @mbg.generated
     */
    public String getBzhlsh() {
        return bzhlsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_bzhzjpz_gl.bzhlsh
     *
     * @param bzhlsh the value for xtpz_bzhzjpz_gl.bzhlsh
     *
     * @mbg.generated
     */
    public void setBzhlsh(String bzhlsh) {
        this.bzhlsh = bzhlsh == null ? null : bzhlsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_bzhzjpz_gl.zdmc
     *
     * @return the value of xtpz_bzhzjpz_gl.zdmc
     *
     * @mbg.generated
     */
    public String getZdmc() {
        return zdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_bzhzjpz_gl.zdmc
     *
     * @param zdmc the value for xtpz_bzhzjpz_gl.zdmc
     *
     * @mbg.generated
     */
    public void setZdmc(String zdmc) {
        this.zdmc = zdmc == null ? null : zdmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_bzhzjpz_gl.glsjb
     *
     * @return the value of xtpz_bzhzjpz_gl.glsjb
     *
     * @mbg.generated
     */
    public String getGlsjb() {
        return glsjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_bzhzjpz_gl.glsjb
     *
     * @param glsjb the value for xtpz_bzhzjpz_gl.glsjb
     *
     * @mbg.generated
     */
    public void setGlsjb(String glsjb) {
        this.glsjb = glsjb == null ? null : glsjb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_bzhzjpz_gl.glzd
     *
     * @return the value of xtpz_bzhzjpz_gl.glzd
     *
     * @mbg.generated
     */
    public String getGlzd() {
        return glzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_bzhzjpz_gl.glzd
     *
     * @param glzd the value for xtpz_bzhzjpz_gl.glzd
     *
     * @mbg.generated
     */
    public void setGlzd(String glzd) {
        this.glzd = glzd == null ? null : glzd.trim();
    }
}