package cn.com.gxbolian.databank.entity;

public class XtpzXlcstz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_xlcstz.lsh
     *
     * @mbg.generated
     */
    private String lsh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_xlcstz.zblsh
     *
     * @mbg.generated
     */
    private String zblsh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_xlcstz.xsz
     *
     * @mbg.generated
     */
    private String xsz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_xlcstz.sjz
     *
     * @mbg.generated
     */
    private String sjz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_xlcstz.lsh
     *
     * @return the value of xtpz_xlcstz.lsh
     *
     * @mbg.generated
     */
    public String getLsh() {
        return lsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_xlcstz.lsh
     *
     * @param lsh the value for xtpz_xlcstz.lsh
     *
     * @mbg.generated
     */
    public void setLsh(String lsh) {
        this.lsh = lsh == null ? null : lsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_xlcstz.zblsh
     *
     * @return the value of xtpz_xlcstz.zblsh
     *
     * @mbg.generated
     */
    public String getZblsh() {
        return zblsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_xlcstz.zblsh
     *
     * @param zblsh the value for xtpz_xlcstz.zblsh
     *
     * @mbg.generated
     */
    public void setZblsh(String zblsh) {
        this.zblsh = zblsh == null ? null : zblsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_xlcstz.xsz
     *
     * @return the value of xtpz_xlcstz.xsz
     *
     * @mbg.generated
     */
    public String getXsz() {
        return xsz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_xlcstz.xsz
     *
     * @param xsz the value for xtpz_xlcstz.xsz
     *
     * @mbg.generated
     */
    public void setXsz(String xsz) {
        this.xsz = xsz == null ? null : xsz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_xlcstz.sjz
     *
     * @return the value of xtpz_xlcstz.sjz
     *
     * @mbg.generated
     */
    public String getSjz() {
        return sjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_xlcstz.sjz
     *
     * @param sjz the value for xtpz_xlcstz.sjz
     *
     * @mbg.generated
     */
    public void setSjz(String sjz) {
        this.sjz = sjz == null ? null : sjz.trim();
    }
}