package cn.com.gxbolian.databank.entity;

public class XtpzSjyGxh {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjy_gxh.sjybm
     *
     * @mbg.generated
     */
    private String sjybm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjy_gxh.sjymc
     *
     * @mbg.generated
     */
    private String sjymc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjy_gxh.flbm
     *
     * @mbg.generated
     */
    private String flbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjy_gxh.bz
     *
     * @mbg.generated
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjy_gxh.czybm
     *
     * @mbg.generated
     */
    private String czybm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjy_gxh.sjybm
     *
     * @return the value of xtpz_sjy_gxh.sjybm
     *
     * @mbg.generated
     */
    public String getSjybm() {
        return sjybm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjy_gxh.sjybm
     *
     * @param sjybm the value for xtpz_sjy_gxh.sjybm
     *
     * @mbg.generated
     */
    public void setSjybm(String sjybm) {
        this.sjybm = sjybm == null ? null : sjybm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjy_gxh.sjymc
     *
     * @return the value of xtpz_sjy_gxh.sjymc
     *
     * @mbg.generated
     */
    public String getSjymc() {
        return sjymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjy_gxh.sjymc
     *
     * @param sjymc the value for xtpz_sjy_gxh.sjymc
     *
     * @mbg.generated
     */
    public void setSjymc(String sjymc) {
        this.sjymc = sjymc == null ? null : sjymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjy_gxh.flbm
     *
     * @return the value of xtpz_sjy_gxh.flbm
     *
     * @mbg.generated
     */
    public String getFlbm() {
        return flbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjy_gxh.flbm
     *
     * @param flbm the value for xtpz_sjy_gxh.flbm
     *
     * @mbg.generated
     */
    public void setFlbm(String flbm) {
        this.flbm = flbm == null ? null : flbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjy_gxh.bz
     *
     * @return the value of xtpz_sjy_gxh.bz
     *
     * @mbg.generated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjy_gxh.bz
     *
     * @param bz the value for xtpz_sjy_gxh.bz
     *
     * @mbg.generated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjy_gxh.czybm
     *
     * @return the value of xtpz_sjy_gxh.czybm
     *
     * @mbg.generated
     */
    public String getCzybm() {
        return czybm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjy_gxh.czybm
     *
     * @param czybm the value for xtpz_sjy_gxh.czybm
     *
     * @mbg.generated
     */
    public void setCzybm(String czybm) {
        this.czybm = czybm == null ? null : czybm.trim();
    }
}