package cn.com.gxbolian.databank.entity;

public class XtpzBzhzjpzSc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sc.lsh
	 * @mbg.generated
	 */
	private String lsh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sc.bzhlsh
	 * @mbg.generated
	 */
	private String bzhlsh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sc.zdmc
	 * @mbg.generated
	 */
	private String zdmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sc.zdbm
	 * @mbg.generated
	 */
	private String zdbm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sc.sjlx
	 * @mbg.generated
	 */
	private String sjlx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sc.jhbz
	 * @mbg.generated
	 */
	private String jhbz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sc.xlzdbm
	 * @mbg.generated
	 */
	private String xlzdbm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xtpz_bzhzjpz_sc.zjbz
	 * @mbg.generated
	 */
	private String zjbz;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sc.lsh
	 * @return  the value of xtpz_bzhzjpz_sc.lsh
	 * @mbg.generated
	 */
	public String getLsh() {
		return lsh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sc.lsh
	 * @param lsh  the value for xtpz_bzhzjpz_sc.lsh
	 * @mbg.generated
	 */
	public void setLsh(String lsh) {
		this.lsh = lsh == null ? null : lsh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sc.bzhlsh
	 * @return  the value of xtpz_bzhzjpz_sc.bzhlsh
	 * @mbg.generated
	 */
	public String getBzhlsh() {
		return bzhlsh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sc.bzhlsh
	 * @param bzhlsh  the value for xtpz_bzhzjpz_sc.bzhlsh
	 * @mbg.generated
	 */
	public void setBzhlsh(String bzhlsh) {
		this.bzhlsh = bzhlsh == null ? null : bzhlsh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sc.zdmc
	 * @return  the value of xtpz_bzhzjpz_sc.zdmc
	 * @mbg.generated
	 */
	public String getZdmc() {
		return zdmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sc.zdmc
	 * @param zdmc  the value for xtpz_bzhzjpz_sc.zdmc
	 * @mbg.generated
	 */
	public void setZdmc(String zdmc) {
		this.zdmc = zdmc == null ? null : zdmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sc.zdbm
	 * @return  the value of xtpz_bzhzjpz_sc.zdbm
	 * @mbg.generated
	 */
	public String getZdbm() {
		return zdbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sc.zdbm
	 * @param zdbm  the value for xtpz_bzhzjpz_sc.zdbm
	 * @mbg.generated
	 */
	public void setZdbm(String zdbm) {
		this.zdbm = zdbm == null ? null : zdbm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sc.sjlx
	 * @return  the value of xtpz_bzhzjpz_sc.sjlx
	 * @mbg.generated
	 */
	public String getSjlx() {
		return sjlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sc.sjlx
	 * @param sjlx  the value for xtpz_bzhzjpz_sc.sjlx
	 * @mbg.generated
	 */
	public void setSjlx(String sjlx) {
		this.sjlx = sjlx == null ? null : sjlx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sc.jhbz
	 * @return  the value of xtpz_bzhzjpz_sc.jhbz
	 * @mbg.generated
	 */
	public String getJhbz() {
		return jhbz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sc.jhbz
	 * @param jhbz  the value for xtpz_bzhzjpz_sc.jhbz
	 * @mbg.generated
	 */
	public void setJhbz(String jhbz) {
		this.jhbz = jhbz == null ? null : jhbz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sc.xlzdbm
	 * @return  the value of xtpz_bzhzjpz_sc.xlzdbm
	 * @mbg.generated
	 */
	public String getXlzdbm() {
		return xlzdbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sc.xlzdbm
	 * @param xlzdbm  the value for xtpz_bzhzjpz_sc.xlzdbm
	 * @mbg.generated
	 */
	public void setXlzdbm(String xlzdbm) {
		this.xlzdbm = xlzdbm == null ? null : xlzdbm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xtpz_bzhzjpz_sc.zjbz
	 * @return  the value of xtpz_bzhzjpz_sc.zjbz
	 * @mbg.generated
	 */
	public String getZjbz() {
		return zjbz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xtpz_bzhzjpz_sc.zjbz
	 * @param zjbz  the value for xtpz_bzhzjpz_sc.zjbz
	 * @mbg.generated
	 */
	public void setZjbz(String zjbz) {
		this.zjbz = zjbz == null ? null : zjbz.trim();
	}
}