package cn.com.gxbolian.databank.entity;

public class XtpzSjzdGxh {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjzd_gxh.zdbm
     *
     * @mbg.generated
     */
    private String zdbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjzd_gxh.sjybm
     *
     * @mbg.generated
     */
    private String sjybm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjzd_gxh.zdmc
     *
     * @mbg.generated
     */
    private String zdmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjzd_gxh.ybmc
     *
     * @mbg.generated
     */
    private String ybmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjzd_gxh.ybzd
     *
     * @mbg.generated
     */
    private String ybzd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjzd_gxh.sjlx
     *
     * @mbg.generated
     */
    private String sjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjzd_gxh.jhbz
     *
     * @mbg.generated
     */
    private String jhbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjzd_gxh.bz
     *
     * @mbg.generated
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xtpz_sjzd_gxh.czybm
     *
     * @mbg.generated
     */
    private String czybm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjzd_gxh.zdbm
     *
     * @return the value of xtpz_sjzd_gxh.zdbm
     *
     * @mbg.generated
     */
    public String getZdbm() {
        return zdbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjzd_gxh.zdbm
     *
     * @param zdbm the value for xtpz_sjzd_gxh.zdbm
     *
     * @mbg.generated
     */
    public void setZdbm(String zdbm) {
        this.zdbm = zdbm == null ? null : zdbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjzd_gxh.sjybm
     *
     * @return the value of xtpz_sjzd_gxh.sjybm
     *
     * @mbg.generated
     */
    public String getSjybm() {
        return sjybm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjzd_gxh.sjybm
     *
     * @param sjybm the value for xtpz_sjzd_gxh.sjybm
     *
     * @mbg.generated
     */
    public void setSjybm(String sjybm) {
        this.sjybm = sjybm == null ? null : sjybm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjzd_gxh.zdmc
     *
     * @return the value of xtpz_sjzd_gxh.zdmc
     *
     * @mbg.generated
     */
    public String getZdmc() {
        return zdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjzd_gxh.zdmc
     *
     * @param zdmc the value for xtpz_sjzd_gxh.zdmc
     *
     * @mbg.generated
     */
    public void setZdmc(String zdmc) {
        this.zdmc = zdmc == null ? null : zdmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjzd_gxh.ybmc
     *
     * @return the value of xtpz_sjzd_gxh.ybmc
     *
     * @mbg.generated
     */
    public String getYbmc() {
        return ybmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjzd_gxh.ybmc
     *
     * @param ybmc the value for xtpz_sjzd_gxh.ybmc
     *
     * @mbg.generated
     */
    public void setYbmc(String ybmc) {
        this.ybmc = ybmc == null ? null : ybmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjzd_gxh.ybzd
     *
     * @return the value of xtpz_sjzd_gxh.ybzd
     *
     * @mbg.generated
     */
    public String getYbzd() {
        return ybzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjzd_gxh.ybzd
     *
     * @param ybzd the value for xtpz_sjzd_gxh.ybzd
     *
     * @mbg.generated
     */
    public void setYbzd(String ybzd) {
        this.ybzd = ybzd == null ? null : ybzd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjzd_gxh.sjlx
     *
     * @return the value of xtpz_sjzd_gxh.sjlx
     *
     * @mbg.generated
     */
    public String getSjlx() {
        return sjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjzd_gxh.sjlx
     *
     * @param sjlx the value for xtpz_sjzd_gxh.sjlx
     *
     * @mbg.generated
     */
    public void setSjlx(String sjlx) {
        this.sjlx = sjlx == null ? null : sjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjzd_gxh.jhbz
     *
     * @return the value of xtpz_sjzd_gxh.jhbz
     *
     * @mbg.generated
     */
    public String getJhbz() {
        return jhbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjzd_gxh.jhbz
     *
     * @param jhbz the value for xtpz_sjzd_gxh.jhbz
     *
     * @mbg.generated
     */
    public void setJhbz(String jhbz) {
        this.jhbz = jhbz == null ? null : jhbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjzd_gxh.bz
     *
     * @return the value of xtpz_sjzd_gxh.bz
     *
     * @mbg.generated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjzd_gxh.bz
     *
     * @param bz the value for xtpz_sjzd_gxh.bz
     *
     * @mbg.generated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xtpz_sjzd_gxh.czybm
     *
     * @return the value of xtpz_sjzd_gxh.czybm
     *
     * @mbg.generated
     */
    public String getCzybm() {
        return czybm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xtpz_sjzd_gxh.czybm
     *
     * @param czybm the value for xtpz_sjzd_gxh.czybm
     *
     * @mbg.generated
     */
    public void setCzybm(String czybm) {
        this.czybm = czybm == null ? null : czybm.trim();
    }
}