package cn.com.gxbolian.databank.dao;

import cn.com.gxbolian.databank.entity.XtpzSjglys;
import cn.com.gxbolian.databank.entity.XtpzSjglysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XtpzSjglysMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjglys
	 * @mbg.generated
	 */
	long countByExample(XtpzSjglysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjglys
	 * @mbg.generated
	 */
	int deleteByExample(XtpzSjglysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjglys
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String lsh);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjglys
	 * @mbg.generated
	 */
	int insert(XtpzSjglys record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjglys
	 * @mbg.generated
	 */
	int insertSelective(XtpzSjglys record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjglys
	 * @mbg.generated
	 */
	List<XtpzSjglys> selectByExample(XtpzSjglysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjglys
	 * @mbg.generated
	 */
	XtpzSjglys selectByPrimaryKey(String lsh);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjglys
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") XtpzSjglys record, @Param("example") XtpzSjglysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjglys
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") XtpzSjglys record, @Param("example") XtpzSjglysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjglys
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(XtpzSjglys record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjglys
	 * @mbg.generated
	 */
	int updateByPrimaryKey(XtpzSjglys record);
}