package cn.com.gxbolian.databank.dao;

import cn.com.gxbolian.databank.entity.XtpzXlcstz;
import cn.com.gxbolian.databank.entity.XtpzXlcstzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XtpzXlcstzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_xlcstz
     *
     * @mbg.generated
     */
    long countByExample(XtpzXlcstzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_xlcstz
     *
     * @mbg.generated
     */
    int deleteByExample(XtpzXlcstzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_xlcstz
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String lsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_xlcstz
     *
     * @mbg.generated
     */
    int insert(XtpzXlcstz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_xlcstz
     *
     * @mbg.generated
     */
    int insertSelective(XtpzXlcstz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_xlcstz
     *
     * @mbg.generated
     */
    List<XtpzXlcstz> selectByExample(XtpzXlcstzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_xlcstz
     *
     * @mbg.generated
     */
    XtpzXlcstz selectByPrimaryKey(String lsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_xlcstz
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") XtpzXlcstz record, @Param("example") XtpzXlcstzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_xlcstz
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") XtpzXlcstz record, @Param("example") XtpzXlcstzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_xlcstz
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(XtpzXlcstz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_xlcstz
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XtpzXlcstz record);
}