package cn.com.gxbolian.databank.dao;

import cn.com.gxbolian.databank.entity.XtpzBzhzjpzSc;
import cn.com.gxbolian.databank.entity.XtpzBzhzjpzScExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XtpzBzhzjpzScMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sc
	 * @mbg.generated
	 */
	long countByExample(XtpzBzhzjpzScExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sc
	 * @mbg.generated
	 */
	int deleteByExample(XtpzBzhzjpzScExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sc
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String lsh);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sc
	 * @mbg.generated
	 */
	int insert(XtpzBzhzjpzSc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sc
	 * @mbg.generated
	 */
	int insertSelective(XtpzBzhzjpzSc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sc
	 * @mbg.generated
	 */
	List<XtpzBzhzjpzSc> selectByExample(XtpzBzhzjpzScExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sc
	 * @mbg.generated
	 */
	XtpzBzhzjpzSc selectByPrimaryKey(String lsh);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sc
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") XtpzBzhzjpzSc record, @Param("example") XtpzBzhzjpzScExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sc
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") XtpzBzhzjpzSc record, @Param("example") XtpzBzhzjpzScExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sc
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(XtpzBzhzjpzSc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sc
	 * @mbg.generated
	 */
	int updateByPrimaryKey(XtpzBzhzjpzSc record);
}