package cn.com.gxbolian.databank.dao;

import cn.com.gxbolian.databank.entity.XtpzXlcs;
import cn.com.gxbolian.databank.entity.XtpzXlcsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XtpzXlcsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_xlcs
	 * @mbg.generated
	 */
	long countByExample(XtpzXlcsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_xlcs
	 * @mbg.generated
	 */
	int deleteByExample(XtpzXlcsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_xlcs
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String lsh);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_xlcs
	 * @mbg.generated
	 */
	int insert(XtpzXlcs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_xlcs
	 * @mbg.generated
	 */
	int insertSelective(XtpzXlcs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_xlcs
	 * @mbg.generated
	 */
	List<XtpzXlcs> selectByExample(XtpzXlcsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_xlcs
	 * @mbg.generated
	 */
	XtpzXlcs selectByPrimaryKey(String lsh);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_xlcs
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") XtpzXlcs record, @Param("example") XtpzXlcsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_xlcs
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") XtpzXlcs record, @Param("example") XtpzXlcsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_xlcs
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(XtpzXlcs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_xlcs
	 * @mbg.generated
	 */
	int updateByPrimaryKey(XtpzXlcs record);
}