package cn.com.gxbolian.databank.dao;

import cn.com.gxbolian.databank.entity.XtpzSjyGxh;
import cn.com.gxbolian.databank.entity.XtpzSjyGxhExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XtpzSjyGxhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy_gxh
     *
     * @mbg.generated
     */
    long countByExample(XtpzSjyGxhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy_gxh
     *
     * @mbg.generated
     */
    int deleteByExample(XtpzSjyGxhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy_gxh
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sjybm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy_gxh
     *
     * @mbg.generated
     */
    int insert(XtpzSjyGxh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy_gxh
     *
     * @mbg.generated
     */
    int insertSelective(XtpzSjyGxh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy_gxh
     *
     * @mbg.generated
     */
    List<XtpzSjyGxh> selectByExample(XtpzSjyGxhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy_gxh
     *
     * @mbg.generated
     */
    XtpzSjyGxh selectByPrimaryKey(String sjybm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy_gxh
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") XtpzSjyGxh record, @Param("example") XtpzSjyGxhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy_gxh
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") XtpzSjyGxh record, @Param("example") XtpzSjyGxhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy_gxh
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(XtpzSjyGxh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjy_gxh
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XtpzSjyGxh record);
}