package cn.com.gxbolian.databank.dao;

import cn.com.gxbolian.databank.entity.XtpzSjzd;
import cn.com.gxbolian.databank.entity.XtpzSjzdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XtpzSjzdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjzd
	 * @mbg.generated
	 */
	long countByExample(XtpzSjzdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjzd
	 * @mbg.generated
	 */
	int deleteByExample(XtpzSjzdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjzd
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String zdbm);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjzd
	 * @mbg.generated
	 */
	int insert(XtpzSjzd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjzd
	 * @mbg.generated
	 */
	int insertSelective(XtpzSjzd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjzd
	 * @mbg.generated
	 */
	List<XtpzSjzd> selectByExample(XtpzSjzdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjzd
	 * @mbg.generated
	 */
	XtpzSjzd selectByPrimaryKey(String zdbm);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjzd
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") XtpzSjzd record, @Param("example") XtpzSjzdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjzd
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") XtpzSjzd record, @Param("example") XtpzSjzdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjzd
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(XtpzSjzd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_sjzd
	 * @mbg.generated
	 */
	int updateByPrimaryKey(XtpzSjzd record);
}