package cn.com.gxbolian.databank.dao;

import cn.com.gxbolian.databank.entity.XtpzBzhzjpzSr;
import cn.com.gxbolian.databank.entity.XtpzBzhzjpzSrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XtpzBzhzjpzSrMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sr
	 * @mbg.generated
	 */
	long countByExample(XtpzBzhzjpzSrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sr
	 * @mbg.generated
	 */
	int deleteByExample(XtpzBzhzjpzSrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sr
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String lsh);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sr
	 * @mbg.generated
	 */
	int insert(XtpzBzhzjpzSr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sr
	 * @mbg.generated
	 */
	int insertSelective(XtpzBzhzjpzSr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sr
	 * @mbg.generated
	 */
	List<XtpzBzhzjpzSr> selectByExample(XtpzBzhzjpzSrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sr
	 * @mbg.generated
	 */
	XtpzBzhzjpzSr selectByPrimaryKey(String lsh);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sr
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") XtpzBzhzjpzSr record, @Param("example") XtpzBzhzjpzSrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sr
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") XtpzBzhzjpzSr record, @Param("example") XtpzBzhzjpzSrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sr
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(XtpzBzhzjpzSr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xtpz_bzhzjpz_sr
	 * @mbg.generated
	 */
	int updateByPrimaryKey(XtpzBzhzjpzSr record);
}