package cn.com.gxbolian.databank.dao;

import cn.com.gxbolian.databank.entity.XtpzSjglysGxh;
import cn.com.gxbolian.databank.entity.XtpzSjglysGxhExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XtpzSjglysGxhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjglys_gxh
     *
     * @mbg.generated
     */
    long countByExample(XtpzSjglysGxhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjglys_gxh
     *
     * @mbg.generated
     */
    int deleteByExample(XtpzSjglysGxhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjglys_gxh
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String lsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjglys_gxh
     *
     * @mbg.generated
     */
    int insert(XtpzSjglysGxh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjglys_gxh
     *
     * @mbg.generated
     */
    int insertSelective(XtpzSjglysGxh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjglys_gxh
     *
     * @mbg.generated
     */
    List<XtpzSjglysGxh> selectByExample(XtpzSjglysGxhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjglys_gxh
     *
     * @mbg.generated
     */
    XtpzSjglysGxh selectByPrimaryKey(String lsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjglys_gxh
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") XtpzSjglysGxh record, @Param("example") XtpzSjglysGxhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjglys_gxh
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") XtpzSjglysGxh record, @Param("example") XtpzSjglysGxhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjglys_gxh
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(XtpzSjglysGxh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_sjglys_gxh
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XtpzSjglysGxh record);
}