package cn.com.gxbolian.databank.dao;

import cn.com.gxbolian.databank.entity.XtpzBzhzjpzGl;
import cn.com.gxbolian.databank.entity.XtpzBzhzjpzGlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XtpzBzhzjpzGlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    long countByExample(XtpzBzhzjpzGlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    int deleteByExample(XtpzBzhzjpzGlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String lsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    int insert(XtpzBzhzjpzGl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    int insertSelective(XtpzBzhzjpzGl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    List<XtpzBzhzjpzGl> selectByExample(XtpzBzhzjpzGlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    XtpzBzhzjpzGl selectByPrimaryKey(String lsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") XtpzBzhzjpzGl record, @Param("example") XtpzBzhzjpzGlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") XtpzBzhzjpzGl record, @Param("example") XtpzBzhzjpzGlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(XtpzBzhzjpzGl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpz_bzhzjpz_gl
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XtpzBzhzjpzGl record);
}